### ISSUE TITLE
Provide a configuration for the output branch

### ISSUE THREAD

**Issue by patrek** [manoelcampos/asciidoctor-ghpages-action#10]
In some cases, we do not want to publish to github pages.

**Comment by manoelcampos** [comment]
Sorry for the late reply.
Do you want to publish to a branch with existing content?
Because as it's alerted on README, the action wipes out the gh-pages branch
before pushing the new changes.

**Comment by manoelcampos** [comment]
The gh-pages branch is not wiped out anymore. Anyway, I'd like to understand your use case.
