### ISSUE TITLE
Feature Request: Any chance we could add asciibuild?

### ISSUE THREAD

**Issue by Bruno-366** [manoelcampos/asciidoctor-ghpages-action#15]
[asciibuild] seems like a really good option if one wants to do literate programming, I suspect that in order to add it to this action the easiest thing would be to ask [asciidoctor/docker-asciidoctor] to include it in their dockfile?

[asciibuild]: https://github.com/jbrisbin/asciibuild
[asciidoctor/docker-asciidoctor]: https://github.com/asciidoctor/docker-asciidoctor

Here is asciibuild's dockfile from the building [instructions]

[instructions]: https://github.com/jbrisbin/asciibuild/blob/master/doc/BUILD.adoc#building-with-docker

```
FROM alpine
RUN apk add --no-cache bash make build-base ruby ruby-rdoc ruby-irb ruby-bundler ruby-dev py-pip docker
RUN pip install pygments

RUN mkdir -p {{workdir}}
COPY . {{workdir}}/
WORKDIR {{workdir}}
RUN bundle install
RUN gem build asciibuild.gemspec
RUN gem install ./asciibuild-*.gem -l
RUN rm -Rf {{workdir}}
RUN apk del build-base make ruby-dev

VOLUME /usr/src
WORKDIR /usr/src

ENTRYPOINT ["asciibuild"]
```

One issue I could see arising is that in order to execute the pieces of code in a literate programming document is that environment needs to have installed that programming language, and so there would need to be a way to configure the docker image so that it includes the programming languages that are used by the literate programming document.

**Comment by manoelcampos** [comment]
I had never heard about literate programming, despite it's a pretty old Donald Knuth thing :smile:.
I checked the examples on asciibuild and it's really amazing. It opens a world of possibilities.
However, installing asciibuild inside the container may slow down the build process. 
Maybe the best option is to request docker-asciidoctor to include it.
Please give it a try and let me know what you could get.

**Comment by Bruno-366** [comment]
absolutely! :)

**Comment by manoelcampos** [comment]
Any updates on that? 
If you get asciibuild installed by default on the docker container, you can just use the new `post_build` parameter.

**Comment by Bruno-366** [comment]
haven't gotten any response from docker-asciidoctor

**Comment by manoelcampos** [comment]
In this case, maybe a `pre_build` parameter would fix the issue. This way, you could install anything you want in your own container. What do you think?

**Comment by manoelcampos** [comment]
The `pre_build` parameter was introduced in #21.
Closing this issue.

**Comment by manoelcampos** [comment]
Please let me know if you can manage to install asciibuild using the new `pre_build` parameter.
I'd love to try it.

**Comment by Bruno-366** [comment]
ok i'll try 👍
