### ISSUE TITLE
How can I publish different page to gh-pages

### ISSUE THREAD

**Issue by byteshiva** [manoelcampos/asciidoctor-ghpages-action#20]
As of now, I see it's picking up README.md and renaming to index.html and later publishes to gh-pages. Can I point different file, maybe a generated asciidoc html to gh-pages.

**Comment by byteshiva** [comment]
I made it work by adding these uncalled steps. 
```
 post_build: 'asciidoctor latest.adoc -o index.html;touch index.html; pwd; ls -lrt; git add -f index.html'
```

I see you are expecting README.html, my use-case, I don't want all the contents to be in README.adoc instead I wanted in separate file say latest.adoc. The question can I pass this file in command line arguements.

```
    for FILE in `find . -name "README.html"`; do 
        ln -s "$FILE" "`dirname $FILE`/index.html"; 
    done
```

**Comment by manoelcampos** [comment]
It builds any existing `.adoc` files. It just creates an index.html  symlink to every README.html.
README is the default main file for every directory in GitHub.
I don't get why you don't have your main files named like that.
If you don't have a README, nothing is shown when you open a directory directly on GitHub interface.
Anyway, I think you can just change your `post_build` command to simply:

```bash
for FILE in `find . -name "latest.html"`; do  ln -sf "$FILE" "`dirname $FILE`/index.html"; done
```

But tell me more about your use case.

**Comment by byteshiva** [comment]
I'm experimenting with webpage generation for the different use cases, 

1. Typical Resume generation with custom layouts and themes based on rules engines. With rules engines, I can show different resume types for custom users.

As of now, I see I can not change themes for pdf generations. I'm using the below to generate custom pages. Also, I do not wish to show lengthy pages on README.adoc or README.md 
```
asciidoctor latest.adoc -o index.html;touch index.html;asciidoctor-pdf -a pdf-stylesdir=themes -a pdf-style=resume -a pdf-fontsdir=fonts latest.adoc -o latest.pdf; git add -f index.html latest.pdf'
```

2. I do not plan to use gh-pages for blog page generation, I understand in this case it would make sense to use README.md as the default page for all listed subdirectories.

**Comment by manoelcampos** [comment]
You don't need to have lengthy READMEs. They can link to other files. But I don't get why you need main files with a different name. Convention over Configuration (CoC) concept helps reducing complexity.

Anyway, additional params were already available before that PR. Check if they can help you.

**Comment by byteshiva** [comment]
Thanks, its in early stage of prototype engineering. Eventually it'll get stable.

The commit helps.
