### ISSUE TITLE
Unable to post-process HTML produced by AsciiDoctor

### ISSUE THREAD

**Issue by brianary** [manoelcampos/asciidoctor-ghpages-action#23]
I've got a table that needs to be wider than the hard width limit imposed by the AsciiDoctor conversion, so I've added [a `post_build`](https://github.com/brianary/brianary.github.io/blob/main/.github/workflows/asciidoctor-ghpages.yml#L33 "sed -i 's/max-width:62[.]5em;//' csharp-history.html") command to update the HTML file, but it doesn't work (I've tried it locally, so I know the command is fine). I still have to manually edit the HTML file on the `gh-pages` branch.

Is there something else that I need to add?

**Comment by manoelcampos** [comment]
Have you checked the CI log for error messages?
Provide a link to your workflow run here.

**Comment by brianary** [comment]
I'm not getting any errors. Here is the most recent run: https://github.com/brianary/brianary.github.io/actions/runs/1524351226

Thanks!

**Comment by manoelcampos** [comment]
Hey @brianary
Thanks for reporting. The changes performed by the post-processing were not being added to gh-pages.
Now the CI log shows when the post-processing is performed and executes the git add at the right place.
Check the new [v2.13 release](https://github.com/manoelcampos/asciidoctor-ghpages-action/releases/tag/v2.1.3) and let me know if it works fine.

**Comment by manoelcampos** [comment]
Since you are using asciidoctor-ghpages-action@v2, just try to rerun your workflow.

**Comment by brianary** [comment]
Works great now! Thanks!
