### ISSUE TITLE
Action keeps failing after latest update

### ISSUE THREAD

**Issue by bossiernesto** [manoelcampos/asciidoctor-ghpages-action#26]
I've been using lately this workflow without any issue but today i'm starting to see the failures as soon as is try to build the `adocs` to generate the gh-page contetnt. This is the latest run i did.

https://github.com/mumuki/cspec/runs/5696563693?check_suite_focus=true

The `yml` i'm currently using is on https://github.com/mumuki/cspec/blob/fix-pipeline/.github/workflows/asciidoctor-ghpages.yml

**Comment by manoelcampos** [comment]
Have you tried to rerun your workflow? 
It was failing for me, but it's not now.

**Comment by manoelcampos** [comment]
I'm working on it

**Comment by manoelcampos** [comment]
I've just reverted the changes. They were just code refactoring.
But unfortunately, something is wrong and no error message is shown.
Use the previous v2.2.0.

[Act](https://github.com/nektos/act) is not working for me anymore to test the action locally.
Sorry for the trouble and thanks for reporting.
