### ISSUE TITLE
Action fails if source dir is set

### ISSUE THREAD

**Issue by bengeser** [manoelcampos/asciidoctor-ghpages-action#27]
Hey there,

since the last update, our company is experiencing issues when running the action.
It seems [line 40 of entrypoint.sh (the find command)](https://github.com/manoelcampos/asciidoctor-ghpages-action/blob/00fa3ad1a4c3ab77e883df20bc815bef2163473c/entrypoint.sh#L40) returns a non-zero exit code if there are folders with subdirectories to delete, as the parent folder might be deleted first and subsequent calls to remove the child directories cause errors.
This would not really be a problem as the deletion succeeds de facto, but the non-zero exit code of `find` results in a termination of the action. This might be, because `-e` is set.  

The Problem could be countered by using 
```
find . -not -path './.git*' -not -name '.' -exec rm -rf {} \; || true
```
instead

Best regards

**Comment by manoelcampos** [comment]
Hello @bengeser, thanks for reporting.
The issue has just been fixed.
If you are using v2 release, just rerun your workflow.
Otherwise, update to v2.2.1.
