### ISSUE TITLE
how can one include docinfo header and footer in workflow?

### ISSUE THREAD

**Issue by jaypatelani** [manoelcampos/asciidoctor-ghpages-action#28]
i tried adding header using docinfo https://docs.asciidoctor.org/asciidoctor/latest/docinfo/ but build fails with 
"Configure git
fatal: --local can only be used inside a git repository"

Thanks,

**Comment by gabrielsr** [comment]
The same started occurring to me.

**Comment by manoelcampos** [comment]
Hello guys
I've never used this docinfo feature.
Nothing has changed on the action lately. Maybe it's something related to the container it used, version of tools and things like that.

Can something share the link to a repo where the issue occurs?

**Comment by manoelcampos** [comment]
The issue was because the git version inside the container was updated and some behaviors changed,
requiring the action to be updated.

I'll try to make the container version fixed to avoid such a kind of surprise.
Thank you all for reporting.
Just try to rerun your workflows and it may work.
