### ISSUE TITLE
Live Demo Unavailable

### ISSUE THREAD

**Issue by Ellipse0934** [manoelcampos/asciidoctor-ghpages-action#41]
It appears that workflow deployment https://manoelcampos.com/asciidoctor-ghpages-action/ is unreachable.
![image](https://github.com/manoelcampos/asciidoctor-ghpages-action/assets/7466364/45b2016b-e12d-40e2-89b0-d04505396c99)

Don't have a screenshot but a few days ago I noticed it being redirected to a gambling site. Perhaps we should move it to github hosted pages ?

**Comment by manoelcampos** [comment]
Thanks for reporting. Current address is https://manoelcampos.github.io/asciidoctor-ghpages-action. I've just updated it.
