### ISSUE TITLE
How to add a `CNAME` file to the `gh-pages` branch

### ISSUE THREAD

**Issue by McPringle** [manoelcampos/asciidoctor-ghpages-action#44]
I use asciidoc and the `asciidoctor-ghpages-action` to publish a documentation website with a custom domain. The custom domain on GitHub needs a `CNAME` file in the root of the `gh-pages` branch. If I put the file there manually, it gets deleted at the next action run.

**Comment by manoelcampos** [comment]
Include the CNAME file in the main branch and it may be included in the gh-pages branch too. Just give it a try and let me know.

**Comment by McPringle** [comment]
No, sorry, that did not work. I placed it in the root of the `main` branch but it did not get copied over.

**Comment by McPringle** [comment]
Analyzing your source I found a solution that worked for me:

```yml
pre_build: echo "infra.ijug.eu" > CNAME && git add -f CNAME
```

Nevertheless it would be more convenient to keep a `CNAME` file, that already exists on the `gh-pages` branch. Why? Because a repository owner would usually go to the pages setting in his repository to configure the custom domain. That's what the GitHub documentation tells the people to do. This will automatically create a `CNAME` file on the `gh-pages` branch.

Running this action deletes this file and therefore the custom domain configuration from the repository. Even when the docs contain a warning that everything of the `gh-pages` branch gets wiped out, a lot of people did not know that configuring a custom domain in the GitHub Web UI will add a file to the `gh-pages` branch. And they won't recognize it, because they are working on the `main` branch.

**Comment by manoelcampos** [comment]
That shouldn't be required. Are you creating setting a source_dir? If that is the case, the CNAME file must be inside that directory. Check this [example](https://github.com/manoelcampos/adoc-ghpages-test). I'm setting the docs as source_dir. Therefore, the CNAME file is inside that dir and it's copied to the gh-pages branch

**Comment by McPringle** [comment]
Thank you very much, putting the `CNAME` file in the `source_dir` works! I updated my PR where I added a FAQ section to your README file.
