### ISSUE TITLE
Passing --signoff flag through to git commit.

### ISSUE THREAD

**Issue by k-wall** [manoelcampos/asciidoctor-ghpages-action#47]
Hello, our [project](https://kroxylicious.io/) is using your action to publish the our documentation, so first off, thank you for the action.

We'd like to adopt [DCO](https://wiki.linuxfoundation.org/dco) our project with automated enforcement (https://probot.github.io/apps/dco/).

I notice that the git commit used by [asciidoctor-ghpages-action](https://github.com/manoelcampos/asciidoctor-ghpages-action) doesn't pass the --signoff flag, I'm expecting the action to break once the switch is thrown.

Would you be open to PR that allows --signoff to be enabled?

**Comment by manoelcampos** [comment]
Yes, I would. But that should be disabled by default

**Comment by k-wall** [comment]
Sorry, I realise I have made a mistake.  The commit made by the action is subjected to the DCO check at all.   This feature isn't useful.
