### ISSUE TITLE
The runs.using key in action.yml must be one of: [docker node12], got composite

### ISSUE THREAD

**Issue by jgeluk** [manoelcampos/asciidoctor-ghpages-action#5]
When running the job locally using https://github.com/nektos/act I get the following error:

```
[asciidoctor-ghpages/build] ⭐  Run manoelcampos/asciidoctor-ghpages-action@v1.3.0
[asciidoctor-ghpages/build]   ☁  git clone 'https://github.com/manoelcampos/asciidoctor-ghpages-action' # ref=v1.3.0
[asciidoctor-ghpages/build]   ❌  Failure - manoelcampos/asciidoctor-ghpages-action@v1.3.0
Error: The runs.using key in action.yml must be one of: [docker node12], got composite
```

Would be good to have support for `act` since it would allow for easy local before-commit testing.

**Comment by manoelcampos** [comment]
Yeah. I'm new to this GitHub Actions thing. I suppose I have to change the action to use a docker container instead.

**Comment by manoelcampos** [comment]
Could you please try the v2.0.0 version to check if it works for you?
The code is available at the v2 branch.
Everything seems to work fine, but the process hangs at the last line of the `entrypoint.sh`,
when I try to push the changes to remote.

**Comment by manoelcampos** [comment]
After changing the action to a docker type, it works perfectly on GitHub servers, but not locally using the nektos/act. 
I think the issue is with the checkout process.

**Comment by manoelcampos** [comment]
In the end, I figured out what was wrong.
If you run the action inside GitHub's servers, the container authenticates using an ssh key.
But if you are running the action locally, you need to authenticate via https using a GitHub Personal Access Token.
Check PR #6 for details.
