### ISSUE TITLE
Publishing only single HTML file to gh-pages

### ISSUE THREAD

**Issue by Gamadril** [manoelcampos/asciidoctor-ghpages-action#8]
I'm using your action in my project: https://github.com/Gamadril/lightoros/blob/master/.github/workflows/doc_publisher.yml but I'm not sure if I'm doing it right.
When I check the gh-pages branch: https://github.com/Gamadril/lightoros/tree/gh-pages I see the content of the master branch, but with generated HTML doc in the `doc` folder. But actually what I would like to see there is only one single index.html file and nothing else. Is it possible to achieve that behaviour with your action?

**Comment by Gamadril** [comment]
I checked the script and I think it cannot do what I want. I found another solution, so I close the issue. On the other hand I still don't understand why the whole content of the master branch is published to gh-pages instead of HTML output only.

**Comment by manoelcampos** [comment]
The entire content is published to gh-pages because you can link to files there.
If you have an image or any other kind of file that is linked into your adoc files, they must be published in the gh-pages branch too, or you get broken links.

**Comment by manoelcampos** [comment]
However, I'll think of some configuration to provide more flexibility.

**Comment by manoelcampos** [comment]
I've created issue #9 but I don't have the time to implement that in the short term.
