### ISSUE TITLE
Include parameter to define the source directory

### ISSUE THREAD

**Issue by manoelcampos** [manoelcampos/asciidoctor-ghpages-action#9]

**Comment by Gamadril** [comment]
In most cases it might be enough to publish just a content of a folder as root content of gh-pages. Linked/embedded images has to be in the same folder/subfolder so the relative paths would work.

**Comment by manoelcampos** [comment]
This depends on what you are doing. If you publish ebooks that link to different kind of files such as source code files, it's really required to include those files on gh-pages.

**Comment by Gamadril** [comment]
well, for me "gh-pages" = HTML. At the end is gh-pages serving web pages. it's not a container for publishing any type of asciidoctor output. In that case the github action must have another name and be just an "intermediate step"...

**Comment by manoelcampos** [comment]
If you use markdown with gh-pages, you'll see there is an option to publish your page from the master branch. This way, everything there will be available, including source code that may be linked in your README files.
Therefore, it's not done particular use case I have.
